#!/bin/sh

USER=$(id -u)
GROUP=$(getent group docker | cut -d: -f3)
CURDIR=$(pwd)

mkdir -p $HOME/.ft

MOUNT_FLAGS=" -v /var/run/docker.sock:/var/run/docker.sock -v $HOME:/user -v $CURDIR:/local  --user $USER:$GROUP"

docker run $FT_DOCKER --network host $MOUNT_FLAGS ocamlpro/ft /bin/tonos-cli "$@"
